version: '3'
services:
  web:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./frontend:/app/frontend:ro
      - ./uploads:/app/uploads       # ← 追加
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads       # ← 追加
    depends_on:
      - redis

  redis:
    image: redis:alpine

