version: '3'
services:
  web:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./frontend:/frontend:ro
    depends_on:
      - redis

  worker:
    build: ./backend
    command: sh celery_worker.sh
    depends_on:
      - redis

  redis:
    image: redis:alpine

