version: '3'
services:
  web:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:alpine
